name: TEST

on: push

env:
  ACTOR: $GITHUB_ACTOR
  COMMIT_SHA: $GITHUB_SHA
jobs:
  info:
    runs-on: ubuntu-latest
    steps:

      - name: Imprimir el nombre del ACTO
        run: echo $GITHUB_ACTOR

      - name: Imprimir commit SHA
        run: echo $GITHUB_SHA
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Imprimir lo mismo pero con la propiedad del github
        run: |
          echo ${{ github.actor }}
          echo ${{ github.sha }}
  test2:
    runs-on: ubuntu-latest
    steps:
      - name: imprimir valores usando env
        run: |
          echo "$ACTOR"
          echo ${{ env.COMMIT_SHA }} 
        
